### PR TITLE
Update harness tests for sepolia

### PR DESCRIPTION
**Pull request by ytham**
- Adds a new folder in harness tests for Sepolia
- DOES NOT INCLUDE `combo` tests and one tx and receipt test that had some issues with debugging.
- Will cherry pick into `rc1` after coordinating w/ Jing

### CODE REVIEW

**Review by jonathanpwang — CHANGES_REQUESTED** [review]
Can we have the output

**Review by jonathanpwang — CHANGES_REQUESTED** [review]
Can we have the `*.output.json` include the `sourceChainId` as a field? I realized from the output itself it's hard to recover which chain it's for.

**Comment by ytham** [comment]
@jonathanpwang this is ready for review again

**Review by jonathanpwang — APPROVED** [review]
LGTM

**Pull request merged**
