### PR TITLE
feat: check outfile before re-compiling

### PR DESCRIPTION
**Pull request by rpalakkal**
also caches rpc calls (during prove and compile)

### CODE REVIEW

**Comment by ytham** [comment]
@rpalakkal we should have all PRs go to the `develop` branch; additional details coming in the meeting later today

**Review by yi-sun — APPROVED** [review]
LGTM, leaving to @ytham on merge

**Comment by jonathanpwang** [comment]
@ytham reminder to merge

**Review by ytham — APPROVED** [review]
LGTM; sorry my notifications got disabled it seems

**Pull request merged**
