### PR TITLE
fix: input name

### PR DESCRIPTION
**Pull request by rpalakkal**

### CODE REVIEW

**Review by yi-sun — APPROVED** [review]
LGTM, but just want to make sure @ytham sees this to make sure there isn't any issue in another downstream dependency.

**Comment by ytham** [comment]
@yi-sun @rpalakkal unfortunately we have `inputs` instead of `input` all the way down the stack to halo2-wasm; do we want to rename them all to be consistent? (i.e. the *.circuits.ts file will use the `inputs` var, halo2-browser cli also uses `inputs`, and halo2-lib-js uses `inputs` as well). i'm all for doing it for consistency now versus later, but wanted to get your thoughts.

**Comment by yi-sun** [comment]
@ytham -- maybe we can make the CLI flags also `--inputs` and `--outputs` for consistency then?

**Comment by ytham** [comment]
@yi-sun sure, we can do that as well; any preference on your end?

**Comment by yi-sun** [comment]
@ytham -- probably simpler to unify around `--inputs` and `--outputs`.  The main motivation for this PR is just that right now the CLI inputs don't correctly override inputs defined in Typescript, which is blocking for some AxiomTest features

**Pull request closed without merging**
