### PR TITLE
feat: update templates to latest axiom-v2-client

### PR DESCRIPTION
**Pull request by rpalakkal**

### CODE REVIEW

**Review by ytham — APPROVED** [review]
LGTM but we don't want to lock to 0.2.2-rc2.2-alpha.1, which doesn't seem ideal.

**Comment by rpalakkal** [comment]
> LGTM but we don't want to lock to 0.2.2-rc2.2-alpha.1, which doesn't seem ideal.

Ahh yeah, for now I just added that since otherwise it defaults to the (older) `release` deployment. We can change this once everything is finalized?

**Comment by ytham** [comment]
> > LGTM but we don't want to lock to 0.2.2-rc2.2-alpha.1, which doesn't seem ideal.
> 
> Ahh yeah, for now I just added that since otherwise it defaults to the (older) `release` deployment. We can change this once everything is finalized?

alright let's go ahead and do `0.2.2-rc2.2` for now and i'll go ahead and publish rc2.2 shortly with another change

**Review by yi-sun — APPROVED** [review]
LGTM

**Pull request merged**
